# # # Sample configuration
# samples: "config/samples.tsv"
# python_env_path: "conda run -n graphbp_complete python" #"python"  # or path to your conda environment

# Project structure configuration
project_paths:
  base_dir: "."
  external_dir: "external"
  results_dir: "results"
  data_dir: "data"

# Module-specific configurations
modules:
  graphbp:
    path: "external/graphbp/OpenMI/GraphBP/GraphBP"
    trained_model: "trained_model_reduced_dataset_100_epochs"
    output_pattern: "gen_mols_epoch_{epoch}_mols_{num_gen}_bs_{known_binding_site}_pdbid_{pdbid}/sdf"
  
  hope_box:
    path: "external/hope-box"
    scripts_dir: "scripts"
    data_dir: "data"
    models_dir: "models"
    results_dir: "results"
    # results_subdir: "results_epoch_{epoch}_mols_{num_gen}_bs_{known_binding_site}_pdbid_{pdbid}"
  
  vina_box:
    path: "external/vina-box"
    # Add vina-specific paths
  
  equibind:
    path: "external/equibind"
    data_dir: "data"
    scripts_dir: "scripts"
    results_dir: "results"
    experiment_pattern: "experiment_{experiment}_{epoch}_{num_gen}_{known_binding_site}_{pdbid}"

# Pipeline parameters (user-customizable)
parameters:
  epoch: 99
  num_gen: 1000
  known_binding_site: False
  aurora: "B"
  pdbid: "4af3"
  experiment: "E1" #"bmB" #
  skip_generate: True

# Resource settings
resources:
  graphbp:
    mem_mb: 8000
    threads: 4
  hope_box:
    mem_mb: 16000
    threads: 8