# Sample configuration
samples: "config/samples.tsv"
# python_env_path: "conda run -n graphbp_complete python" #"python"  # or path to your conda environment

# GraphBP parameters
trained_model_path: "external/graphbp/OpenMI/GraphBP/GraphBP/trained_model"
epoch: 99
num_gen: 1
known_binding_site: False #"True"
aurora: "B"
pdbid: "4af3"

# Pipeline parameters
hope_box:
  num_gen: 100
  epoch: 50
  known_binding_site: "True"
  aurora: "B"

vina:
  epoch: 50
  num_mols: 100
  batch_size: "1"
  exhaustiveness: 32

# Resource settings
resources:
  graphbp:
    mem_mb: 8000
    threads: 4
  hope_box:
    mem_mb: 16000
    threads: 8
  equibind:
    mem_mb: 32000
    threads: 16
  vina:
    mem_mb: 8000
    threads: 4