# # # Sample configuration
# samples: "config/samples.tsv"
# python_env_path: "conda run -n graphbp_complete python" #"python"  # or path to your conda environment

# # GraphBP parameters
# graphbp:
#   trained_model_path: "external/graphbp/OpenMI/GraphBP/GraphBP/trained_model_reduced_dataset_100_epochs"
#   epoch: 99
#   num_gen: 1
#   known_binding_site: False #"True"
#   aurora: "B"
#   pdbid: "4af3"

# # Pipeline parameters
# hope_box:
#   num_gen: 100
#   epoch: 50
#   known_binding_site: "True"
#   aurora: "B"

# vina:
#   epoch: 50
#   num_mols: 100
#   batch_size: "1"
#   exhaustiveness: 32

# # Resource settings
# resources:
#   graphbp:
#     mem_mb: 8000
#     threads: 4
#   hope_box:
#     mem_mb: 16000
#     threads: 8
#   equibind:
#     mem_mb: 32000
#     threads: 16
#   vina:
#     mem_mb: 8000
#     threads: 4










# Project structure configuration
project_paths:
  base_dir: "."
  external_dir: "external"
  results_dir: "results"
  data_dir: "data"

# Module-specific configurations
modules:
  graphbp:
    path: "external/graphbp/OpenMI/GraphBP/GraphBP"
    trained_model_subdir: "trained_model_reduced_dataset_100_epochs"
    output_pattern: "gen_mols_epoch_{epoch}_mols_{num_gen}_bs_{known_binding_site}_pdbid_{pdbid}/sdf"
  
  hope_box:
    path: "external/hope-box"
    scripts_dir: "scripts"
    data_dir: "data"
    models_dir: "models"
    results_dir: "results"
    # results_subdir: "results_epoch_{epoch}_mols_{num_gen}_bs_{known_binding_site}_pdbid_{pdbid}"
  
  vina:
    path: "external/vina"
    # Add vina-specific paths

# Pipeline parameters (user-customizable)
parameters:
  epoch: 99
  num_gen: 1
  known_binding_site: False
  aurora: "B"
  pdbid: "4af3"

# Resource settings
resources:
  graphbp:
    mem_mb: 8000
    threads: 4
  hope_box:
    mem_mb: 16000
    threads: 8